name: PR AUTO LABEL

on:
  pull_request:
    types: [opened, synchronize, reopened, issue_comment]

jobs:
  run-pr-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install axios

    - name: Run PR script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_ID: ${{ github.event.issue.number }}
        REPO_OWNER: ${{ github.event.repository.owner }}
        REPO_NAME: ${{ github.event.repository.name }}
      run: node .github/scripts/update_label.js
