name: Analyse PRs reviews

"on":
  pull_request_target:
    types: [opened, synchronize]
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write

jobs:
  analyse-reviews:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up jq
      run: sudo apt-get install -y jq

    - name: Run PR script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_ID: ${{ github.event.number || github.event.pull_request.number}}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        GITHUB_EVENT_ACTION: ${{ github.event.action }}
      run: bash .github/scripts/update_label.sh
